spring:
  application:
    name: db

# 数据连接
  datasource:
    url: jdbc:mysql://10.202.12.50:3306/lura
    username: lura
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

# Specify the DBMS
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    




